-- Supabase SQL Schema for Ogun State BPMS (Billing & Payment Management System)
-- Run this in the Supabase SQL Editor (https://app.supabase.com -> Project -> SQL Editor)

-- 1. Create the bills table
CREATE TABLE IF NOT EXISTS public.bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_code TEXT UNIQUE NOT NULL,
    billed_to TEXT NOT NULL,
    bill_description TEXT NOT NULL,
    ministry TEXT NOT NULL DEFAULT 'Internal Revenue Service IRS',
    service TEXT NOT NULL DEFAULT '',
    bill_date TEXT NOT NULL,
    bill_number TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    status TEXT NOT NULL DEFAULT 'Paid',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

-- 3. Create Public Policies (allows read and write without login for static site)
CREATE POLICY "Public Read Bills" 
    ON public.bills FOR SELECT 
    USING (true);

CREATE POLICY "Public Insert Bills" 
    ON public.bills FOR INSERT 
    WITH CHECK (true);

CREATE POLICY "Public Update Bills" 
    ON public.bills FOR UPDATE 
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Public Delete Bills" 
    ON public.bills FOR DELETE 
    USING (true);

-- 4. Seed initial records
INSERT INTO public.bills (payment_code, billed_to, bill_description, ministry, service, bill_date, bill_number, amount, status)
VALUES 
('0094000056959', 'MR ADEYEMI ADEMOLA', 'MINIMUM TAX', 'Internal Revenue Service IRS', 'Minimum Tax', '7th April, 2026', '13388027', 10100.00, 'Paid'),
('0094000056960', 'MRS FOLASHADE BALOGUN', 'LAND USE CHARGE', 'Ministry of Finance', 'Land Use & Building Assessment', '10th April, 2026', '13388028', 35500.00, 'Paid'),
('0094000056961', 'OLAWALE ENTERPRISES LTD', 'BUSINESS PREMISES PERMIT', 'Ministry of Commerce & Industry', 'Business Registration', '12th April, 2026', '13388029', 50000.00, 'Pending'),
('0094000099999', 'CHIEF TUNDE BAKARE', 'DEVELOPMENT LEVY & INFRASTRUCTURE', 'Internal Revenue Service IRS', 'Development Levy', '12th September, 2026', '48435552', 75000.00, 'Paid')
ON CONFLICT (payment_code) DO NOTHING;
